services:
  proxy:
    image: alpine:3.21.0
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - type: bind
        source: ./httpd.conf
        target: /etc/apache2/httpd.conf
    tty: true
